## Web Intelligence 2020 Project
#### Holerga Flavius-Adrian

### Part1: Preparing dataset

In [107]:
import numpy as np # import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [108]:
import warnings
warnings.filterwarnings('ignore')

In [109]:
from os import listdir # make a dataset containing all tables
dataset_dir = './clean_datasets/'
df = pd.concat([pd.read_excel(dataset_dir+f) for f in listdir(dataset_dir)], ignore_index=True,sort=False)

In [110]:
df.head()

ATP  Location              Tournament       Date  Series    Court Surface  \
0    1  Brisbane  Brisbane International 2013-12-30  ATP250  Outdoor    Hard   
1    1  Brisbane  Brisbane International 2013-12-30  ATP250  Outdoor    Hard   
2    1  Brisbane  Brisbane International 2013-12-30  ATP250  Outdoor    Hard   
3    1  Brisbane  Brisbane International 2013-12-30  ATP250  Outdoor    Hard   
4    1  Brisbane  Brisbane International 2013-12-30  ATP250  Outdoor    Hard   

       Round  Best of        Winner  ...   LBW   LBL   PSW   PSL   SJW   SJL  \
0  1st Round        3  Matosevic M.  ...  1.91  1.80  1.88  2.01  1.91  1.80   
1  1st Round        3   Nieminen J.  ...  1.33  3.25  1.35  3.47  1.36  2.88   
2  1st Round        3      Cilic M.  ...  1.44  2.62  1.39  3.22  1.40  2.75   
3  1st Round        3    Querrey S.  ...  1.91  1.80  1.99  1.90  1.91  1.80   
4  1st Round        3   Dimitrov G.  ...  1.33  3.25  1.28  4.01  1.29  3.25   

   MaxW  MaxL  AvgW  AvgL  
0  2.00  2.10  1.82  1.94  
1  1.36  3.80  1.32  3.32  
2  1.44  3.55  1.39  2.93  
3  2.10  1.91  1.92  1.83  
4  1.33  4.33  1.29  3.53  

[5 rows x 42 columns]

In [111]:
# define columns of interest
interest_columns = ['Location','Tournament','Date','Court','Surface','Round','Winner','Loser','WPts',
                    'LPts','WRank','LRank','B365W','B365L','PSW','PSL','MaxW','MaxL']
df=df[interest_columns].copy()

In [112]:
df[['Player1','Player2']] = df.loc[:,['Winner','Loser']]

In [113]:
#create Won collumn - treat the game based on environment and players status
np.random.seed(1999)
Win = np.random.randint(2,size=len(df))

df['Win'] = Win
isWin = (Win==0)
df.loc[isWin,'WRank'] , df.loc[isWin,'LRank'] = df.loc[isWin,'LRank'], df.loc[isWin,'WRank']
df.loc[isWin,'WPts'] , df.loc[isWin,'LPts'] = df.loc[isWin,'LPts'], df.loc[isWin,'WPts']
df.loc[isWin,'Player1'] , df.loc[isWin,'Player2'] = df.loc[isWin,'Player2'], df.loc[isWin,'Player1']

In [114]:
df.loc[df['Win'] == 0].head()

Location              Tournament       Date    Court Surface      Round  \
1  Brisbane  Brisbane International 2013-12-30  Outdoor    Hard  1st Round   
2  Brisbane  Brisbane International 2013-12-30  Outdoor    Hard  1st Round   
3  Brisbane  Brisbane International 2013-12-30  Outdoor    Hard  1st Round   
7  Brisbane  Brisbane International 2013-12-31  Outdoor    Hard  1st Round   
8  Brisbane  Brisbane International 2013-12-31  Outdoor    Hard  1st Round   

        Winner         Loser    WPts    LPts  ...  LRank  B365W  B365L   PSW  \
1  Nieminen J.  Duckworth J.   425.0  1090.0  ...   39.0   1.28   3.50  1.35   
2     Cilic M.    Istomin D.   965.0  1130.0  ...   37.0   1.36   3.00  1.39   
3   Querrey S.   Tursunov D.  1244.0   960.0  ...   46.0   1.90   1.80  1.99   
7     Lopez F.  Kukushkin M.   721.0  1310.0  ...   28.0   1.66   2.10  1.75   
8    Chardy J.  Mannarino A.   784.0  1175.0  ...   34.0   1.44   2.62  1.55   

    PSL  MaxW  MaxL       Player1      Player2 Win  
1  3.47  1.36  3.80  Duckworth J.  Nieminen J.   0  
2  3.22  1.44  3.55    Istomin D.     Cilic M.   0  
3  1.90  2.10  1.91   Tursunov D.   Querrey S.   0  
7  2.18  1.83  2.20  Kukushkin M.     Lopez F.   0  
8  2.60  1.62  2.75  Mannarino A.    Chardy J.   0  

[5 rows x 21 columns]

In [115]:
#factorize
df['Location']=pd.factorize(df['Location'])[0]
df['Court']=pd.factorize(df['Court'])[0]
df['Surface']=pd.factorize(df['Surface'])[0]
df['Round']=pd.factorize(df['Round'])[0]**2

In [116]:
df.head()

Location              Tournament       Date  Court  Surface  Round  \
0         0  Brisbane International 2013-12-30      0        0      0   
1         0  Brisbane International 2013-12-30      0        0      0   
2         0  Brisbane International 2013-12-30      0        0      0   
3         0  Brisbane International 2013-12-30      0        0      0   
4         0  Brisbane International 2013-12-30      0        0      0   

         Winner         Loser    WPts    LPts  ...  LRank  B365W  B365L   PSW  \
0  Matosevic M.  Benneteau J.   774.0  1160.0  ...   35.0   1.72   2.00  1.88   
1   Nieminen J.  Duckworth J.   425.0  1090.0  ...   39.0   1.28   3.50  1.35   
2      Cilic M.    Istomin D.   965.0  1130.0  ...   37.0   1.36   3.00  1.39   
3    Querrey S.   Tursunov D.  1244.0   960.0  ...   46.0   1.90   1.80  1.99   
4   Dimitrov G.      Haase R.  1520.0   977.0  ...   43.0   1.25   3.75  1.28   

    PSL  MaxW  MaxL       Player1       Player2 Win  
0  2.01  2.00  2.10  Matosevic M.  Benneteau J.   1  
1  3.47  1.36  3.80  Duckworth J.   Nieminen J.   0  
2  3.22  1.44  3.55    Istomin D.      Cilic M.   0  
3  1.90  2.10  1.91   Tursunov D.    Querrey S.   0  
4  4.01  1.33  4.33   Dimitrov G.      Haase R.   1  

[5 rows x 21 columns]

### Adding extra criterions
1. Number of wins in the current year up until the game

In [117]:
# create column with number of wins for each players until the date of the game
def nwins_player_before_date(name,cur_date): # wins until game
    c=0
    for i in df.loc[df['Winner']==name].values:
        if cur_date > i[2]:
            c+=1
    return c**2

2. Number of wins in total before game/Number of games in total before game

In [118]:
def raport_player_before_date(name,cur_date): # wins/total games until game in the same year
    c=1
    d=1
    #search = df.loc[cur_date.to_pydatetime().year==pd.DatetimeIndex(df['Date']).year]
    for i in df.loc[df['Winner']==name].values:
        if cur_date > i[2]:
            c+=1
    for i in df.loc[df['Loser']==name].values:
        if cur_date > i[2]:
            d+=1
    return c/(c+d)**2

Add columns to table

In [119]:
def calc_nwins_by_date(my_df): # add 2 cols consisting of player wins per dat year until game
    my_df["P1dW"]=[nwins_player_before_date(name[0],name[1]) for name in my_df[["Player1","Date"]].to_numpy()]
    my_df["P2dW"]=[nwins_player_before_date(name[0],name[1]) for name in my_df[["Player2","Date"]].to_numpy()]
    my_df["P1dR"]=[raport_player_before_date(name[0],name[1]) for name in my_df[["Player1","Date"]].to_numpy()]
    my_df["P2dR"]=[raport_player_before_date(name[0],name[1]) for name in my_df[["Player2","Date"]].to_numpy()]
    return my_df

In [120]:
df = calc_nwins_by_date(df)

In [121]:
df.head()

Location              Tournament       Date  Court  Surface  Round  \
0         0  Brisbane International 2013-12-30      0        0      0   
1         0  Brisbane International 2013-12-30      0        0      0   
2         0  Brisbane International 2013-12-30      0        0      0   
3         0  Brisbane International 2013-12-30      0        0      0   
4         0  Brisbane International 2013-12-30      0        0      0   

         Winner         Loser    WPts    LPts  ...   PSL  MaxW  MaxL  \
0  Matosevic M.  Benneteau J.   774.0  1160.0  ...  2.01  2.00  2.10   
1   Nieminen J.  Duckworth J.   425.0  1090.0  ...  3.47  1.36  3.80   
2      Cilic M.    Istomin D.   965.0  1130.0  ...  3.22  1.44  3.55   
3    Querrey S.   Tursunov D.  1244.0   960.0  ...  1.90  2.10  1.91   
4   Dimitrov G.      Haase R.  1520.0   977.0  ...  4.01  1.33  4.33   

        Player1       Player2  Win  P1dW  P2dW  P1dR  P2dR  
0  Matosevic M.  Benneteau J.    1     0     0  0.25  0.25  
1  Duckworth J.   Nieminen J.    0     0     0  0.25  0.25  
2    Istomin D.      Cilic M.    0     0     0  0.25  0.25  
3   Tursunov D.    Querrey S.    0     0     0  0.25  0.25  
4   Dimitrov G.      Haase R.    1     0     0  0.25  0.25  

[5 rows x 25 columns]

Rearrange columns and ingore uninteresting information

In [122]:
selected_features = ["Winner","Loser","Date","Tournament","Player1","Player2",'WRank','LRank','WPts','LPts','Court','Surface','Round',
        'P1dW','P2dW','P1dR','P2dR',
        'B365W','B365L','PSW','PSL','MaxW','MaxL',
        'Win']
df= df[selected_features]
df.head()

Winner         Loser       Date              Tournament  \
0  Matosevic M.  Benneteau J. 2013-12-30  Brisbane International   
1   Nieminen J.  Duckworth J. 2013-12-30  Brisbane International   
2      Cilic M.    Istomin D. 2013-12-30  Brisbane International   
3    Querrey S.   Tursunov D. 2013-12-30  Brisbane International   
4   Dimitrov G.      Haase R. 2013-12-30  Brisbane International   

        Player1       Player2  WRank  LRank    WPts    LPts  ...  P2dW  P1dR  \
0  Matosevic M.  Benneteau J.   61.0   35.0   774.0  1160.0  ...     0  0.25   
1  Duckworth J.   Nieminen J.  136.0   39.0   425.0  1090.0  ...     0  0.25   
2    Istomin D.      Cilic M.   45.0   37.0   965.0  1130.0  ...     0  0.25   
3   Tursunov D.    Querrey S.   29.0   46.0  1244.0   960.0  ...     0  0.25   
4   Dimitrov G.      Haase R.   23.0   43.0  1520.0   977.0  ...     0  0.25   

   P2dR  B365W  B365L   PSW   PSL  MaxW  MaxL  Win  
0  0.25   1.72   2.00  1.88  2.01  2.00  2.10    1  
1  0.25   1.28   3.50  1.35  3.47  1.36  3.80    0  
2  0.25   1.36   3.00  1.39  3.22  1.44  3.55    0  
3  0.25   1.90   1.80  1.99  1.90  2.10  1.91    0  
4  0.25   1.25   3.75  1.28  4.01  1.33  4.33    1  

[5 rows x 24 columns]

In [123]:
df.fillna(df.mean(), inplace=True) # fill missing data with column mean

training_set = ['WPts','LPts','Court','Surface','Round','P1dW','P2dW','P1dR','P2dR',
                'B365W','B365L','PSW','PSL','MaxW','MaxL']
X = df.loc[pd.DatetimeIndex(df['Date']).year<2019,training_set].values # select data for training [excluding 2019 dataset]
Y = df.loc[pd.DatetimeIndex(df['Date']).year<2019,'Win'].values # select the Win column

In [124]:
#split into test and train data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

### Part2: Applying logistical regression

In [125]:
from sklearn.linear_model import LogisticRegression

In [126]:
logisticRegr = LogisticRegression(solver='lbfgs')
logisticRegr.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [127]:
logisticRegr.predict(x_test)

array([1, 0, 0, ..., 1, 1, 1])

In [128]:
predictions = logisticRegr.predict(x_test)

In [129]:
score = logisticRegr.score(x_test,y_test)
print(score)

0.6546215290985166


### Part3: Random Forest

In [130]:
from sklearn.ensemble import RandomForestClassifier

In [131]:
clf = RandomForestClassifier(n_jobs=2, random_state=0, n_estimators=10)
clf.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=2,
                       oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [132]:
clf.predict(x_test)

array([1, 0, 0, ..., 0, 0, 0])

In [133]:
y_test

array([1, 0, 0, ..., 0, 0, 0])

In [134]:
score = clf.score(x_test,y_test)
print(score)

0.7877519969570179


### Pick best features by Recursive Elimination

In [135]:
from sklearn.feature_selection import RFE

In [136]:
selector = RFE(clf, 8, step=1)
selector = selector.fit(X, Y)
selector.support_

array([ True,  True, False, False, False,  True,  True,  True, False,
       False, False, False,  True,  True,  True])

In [137]:
selected_features = ['WPts','LPts','Court','Surface','Round','P1dW','P2dW','P1dR','P2dR',
                     'B365W','B365L','PSW','PSL','MaxW','MaxL']
# removed 'EXW','EXL','LBW','LBL' because they do not appear in 2019 dataset

is_approved = lambda i : selector.support_[i]==True
selected_features2 = [x for x in selected_features if is_approved(selected_features.index(x))]
selected_features2

['WPts', 'LPts', 'P1dW', 'P2dW', 'P1dR', 'PSL', 'MaxW', 'MaxL']

In [138]:
df[selected_features2].head()

WPts    LPts  P1dW  P2dW  P1dR   PSL  MaxW  MaxL
0   774.0  1160.0     0     0  0.25  2.01  2.00  2.10
1   425.0  1090.0     0     0  0.25  3.47  1.36  3.80
2   965.0  1130.0     0     0  0.25  3.22  1.44  3.55
3  1244.0   960.0     0     0  0.25  1.90  2.10  1.91
4  1520.0   977.0     0     0  0.25  4.01  1.33  4.33

In [139]:
X = df.loc[pd.DatetimeIndex(df['Date']).year<2019,selected_features2].values
Y = df.loc[pd.DatetimeIndex(df['Date']).year<2019,'Win'].values

In [140]:
x_train, x_test, y_train, y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

In [141]:
clf = RandomForestClassifier(n_jobs=2, random_state=0, n_estimators=10)
clf.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=2,
                       oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [142]:
prediction = clf.predict(x_test)
prediction

array([1, 0, 0, ..., 0, 0, 0])

In [143]:
score = clf.score(x_test,y_test)
print("Score for Random Forest:",score)

Score for Random Forest: 0.7907949790794979


And now compared to Logistic Regression

In [144]:
logisticRegr = LogisticRegression(solver='lbfgs')
logisticRegr.fit(x_train,y_train)
score = logisticRegr.score(x_test,y_test)
print("Score for Logistic Regression:",score) # tuned just for Random Forest parameters

Score for Logistic Regression: 0.6546215290985166


### Analyze the predictions for 2019

In [145]:
X = df.loc[pd.DatetimeIndex(df['Date']).year>=2019,selected_features2].values
Y = df[pd.DatetimeIndex(df['Date']).year>=2019]['Win']
clf.predict(X)

array([1, 0, 0, ..., 1, 0, 0])

In [146]:
score = clf.score(X,Y)
score

0.7612803702275357

Now only for Australian Open

In [147]:
df_ao = df.loc[pd.DatetimeIndex(df['Date']).year>=2019]
df_ao = df_ao.loc[df_ao['Tournament'] == 'Australian Open']

df_ao.head()

Winner          Loser       Date       Tournament  \
13265      Anderson K.   Mannarino A. 2019-01-14  Australian Open   
13266  Basilashvili N.     Eubanks C. 2019-01-14  Australian Open   
13267         Albot R.        Mmoh M. 2019-01-14  Australian Open   
13268     Travaglia S.   Andreozzi G. 2019-01-14  Australian Open   
13269      Verdasco F.  Kecmanovic M. 2019-01-14  Australian Open   

             Player1          Player2  WRank  LRank    WPts    LPts  ...  \
13265    Anderson K.     Mannarino A.    6.0   42.0  4810.0  1045.0  ...   
13266     Eubanks C.  Basilashvili N.  170.0   20.0   312.0  1820.0  ...   
13267        Mmoh M.         Albot R.  107.0   98.0   526.0   585.0  ...   
13268   Andreozzi G.     Travaglia S.   77.0  137.0   708.0   401.0  ...   
13269  Kecmanovic M.      Verdasco F.  125.0   28.0   458.0  1410.0  ...   

        P2dW      P1dR      P2dR  B365W  B365L   PSW    PSL  MaxW   MaxL  Win  
13265  16384  0.002120  0.001783   1.06  10.00  1.05  13.28  1.08  13.28    1  
13266   3844  0.030000  0.003457   1.20   4.50  1.24   4.61  1.30   4.66    0  
13267    676  0.015123  0.003567   2.10   1.72  2.19   1.76  2.22   1.77    0  
13268     16  0.019391  0.017301   1.40   3.00  1.45   2.97  1.50   3.02    0  
13269  20164  0.055556  0.001962   1.50   2.62  1.50   2.81  1.50   2.90    0  

[5 rows x 24 columns]

In [148]:
X = df_ao.loc[:,selected_features2]
Y = df_ao[df_ao['Tournament'] == 'Australian Open']['Win']

In [149]:
score = clf.score(X,Y) # for random forest
score

0.8267716535433071

In [150]:
score = logisticRegr.score(X,Y)
score

0.6929133858267716

#### Simulate game

In [151]:
def simulate_game(entries): 
    # gets a df slice with 2 games
    # returns an entry containing the winners of both passed entries
    testing = entries.loc[:,selected_features2]
    prediction = clf.predict(testing.iloc[0:2])
    result = df_ao.loc[:,selected_features2]
    result = df_ao.iloc[:1] # get a line of the table to then change the contents
    
    game1 = entries.iloc[0:1]
    game2 = entries.iloc[1:2]
    
    result.loc[:,'Player1']=game1['Player1'].values[0] if prediction[0]==1 else game1['Player2'].values[0]
    result.loc[:,'WRank']=game1['WRank'].values[0] if prediction[0]==1 else game1['LRank'].values[0]
    result.loc[:,'WPts']=game1['WPts'].values[0] if prediction[0]==1 else game1['LPts'].values[0]
    result.loc[:,'P1dW']=game1['P1dW'].values[0] if prediction[0]==1 else game1['P2dW'].values[0]
    result.loc[:,'P1dR']=game1['P1dR'].values[0] if prediction[0]==1 else game1['P2dR'].values[0]
    result.loc[:,'MaxW']=game1['MaxW'].values[0] if prediction[0]==1 else game1['MaxL'].values[0]
    
    result['Player2']=game2['Player1'].values[0] if prediction[1]==1 else game2['Player2'].values[0]
    result.loc[:,'LRank']=game2['WRank'].values[0] if prediction[1]==1 else game2['LRank'].values[0]
    result.loc[:,'LPts']=game2['WPts'].values[0] if prediction[1]==1 else game2['LPts'].values[0]
    result.loc[:,'P2dW']=game2['P1dW'].values[0] if prediction[1]==1 else game2['P2dW'].values[0]
    result.loc[:,'P2dR']=game2['P1dR'].values[0] if prediction[1]==1 else game2['P2dR'].values[0]
    result.loc[:,'PSL']=game2['PSW'].values[0] if prediction[1]==1 else game2['PSL'].values[0]
    
    result.loc[:,'Winner']='-'
    result.loc[:,'Loser']='-'
    return result

In [152]:
df_ao_r1 = df_ao.loc[df_ao['Round']==0] # just round 1
entry = df_ao_r1.iloc[5].to_numpy() # check for entries to see if model is accurate
entry

array(['Cuevas P.', 'Lajovic D.', Timestamp('2019-01-14 00:00:00'),
       'Australian Open', 'Cuevas P.', 'Lajovic D.', 94.0, 46.0, 616.0,
       1010.0, 0, 0, 0, 12321, 7744, 0.0025887573964497044,
       0.0023167430237401084, 3.2, 1.36, 3.51, 1.35, 3.51, 1.76, 1],
      dtype=object)

In [153]:
X = df_ao_r1.iloc[4:6]
Y= simulate_game(X)
Y

Winner Loser       Date       Tournament      Player1    Player2  WRank  \
13265      -     - 2019-01-14  Australian Open  Verdasco F.  Cuevas P.   28.0   

       LRank    WPts   LPts  ...   P2dW      P1dR      P2dR  B365W  B365L  \
13265   94.0  1410.0  616.0  ...  12321  0.001962  0.002589   1.06   10.0   

        PSW   PSL  MaxW   MaxL  Win  
13265  1.05  3.51   2.9  13.28    1  

[1 rows x 24 columns]

Naive prediction of Australian Open 2019 without considering any distribution rules or other system requirements

The players were selected in order from the dataset and matched in pairs of 2. Then I applied the same rule on the dataset that resulted from the winners from the previous round.

In [154]:
final_game=df_ao_r1
rounds=[]
r_index = 1 # round index
while len(final_game)>1:
    result_table = pd.DataFrame()
    for i in range(0,len(final_game),2):
        result_table=pd.concat([result_table,simulate_game(final_game.iloc[i:i+2])])
    final_game = result_table
    rounds.append(final_game)
    r_index+=1

final_game

Winner Loser       Date       Tournament     Player1    Player2  WRank  \
13265      -     - 2019-01-14  Australian Open  Federer R.  Zverev A.    3.0   

       LRank    WPts    LPts  ...   P2dW     P1dR      P2dR  B365W  B365L  \
13265    4.0  6420.0  6385.0  ...  29241  0.00283  0.002604   1.06   10.0   

        PSW   PSL   MaxW   MaxL  Win  
13265  1.05  1.05  13.28  13.28    1  

[1 rows x 24 columns]

In [155]:
rounds[3]

Winner Loser       Date       Tournament       Player1        Player2  \
13265      -     - 2019-01-14  Australian Open   Anderson K.         Ito T.   
13265      -     - 2019-01-14  Australian Open  Khachanov K.     Federer R.   
13265      -     - 2019-01-14  Australian Open    Fognini F.       Simon G.   
13265      -     - 2019-01-14  Australian Open     Zverev A.  Cecchinato M.   

       WRank  LRank    WPts    LPts  ...   P2dW      P1dR      P2dR  B365W  \
13265    6.0  150.0  4810.0   360.0  ...    196  0.002120  0.009862   1.06   
13265   11.0    3.0  2835.0  6420.0  ...  63504  0.003954  0.002830   1.06   
13265   13.0   30.0  2315.0  1280.0  ...  22801  0.002064  0.001995   1.06   
13265    4.0   18.0  6385.0  1889.0  ...    841  0.002604  0.004931   1.06   

       B365L   PSW    PSL  MaxW   MaxL  Win  
13265   10.0  1.05   1.05  1.08  13.28    1  
13265   10.0  1.05  17.37  1.13  13.28    1  
13265   10.0  1.05   4.43  1.49  13.28    1  
13265   10.0  1.05   1.05  7.60  13.28    1  

[4 rows x 24 columns]

In [156]:
winner = final_game.loc[:,selected_features2]
prediction = clf.predict(winner.iloc[:1])
if(prediction[0]==1):
    print("Winner is", final_game['Player1'].values[0])
else:
    print("Winner is", final_game['Player2'].values[0])

Winner is Zverev A.
